name: "places_ops"
version: "1.0.0"
profile: "app"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  budget_warning_threshold: 0.9

models:
  places_ops:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
